const SLIDE_SHOW_TEXT = [
  "Create a react app however you like. I use create react app here",
  "Head over to app.js. I made a few changes to the boilerplate",
  "Add a components folder and a primary component",
  "Install Chrome Redux DevTools",
  "Create store with middleware then add store to app with provider",
  "Add a reducer folder and a root reducer",
  "Create your first reducer",
  "Add that reducer to your root reducer",
  "The app works!",
  "DevTools show state!",
  "Create a container to glue state",
  "Sample container structure",
  "Pass state as a prop to a visual component",
  "Get frustrated rename a bunch of files and add bootstrap to app",
  "Create stateless component to display passed props",
  "The app works!",
  "Add more characters",
  "Passing state between siblings",
  "Create actions and action types",
  "Create a show spoiler action and action type",
  "Add a reducer to catch new state",
  "Add that reducer to the root reducer",
  "The state is updated and the App works!",
  "Add the action to the switch",
  "Our list view container",
  "Add the action/dispatch to the container and pass it to the visual component",
  "Our list view",
  "Our list view with a button",
  "The app works!",
  "Clicking the button sends an action (with typos)...",
  "...that updates state",
  "One more time! Add a container to the main component",
  "Create that container",
  "Make that visual component! App works?",
]


export default SLIDE_SHOW_TEXT
